micronaut:
  application:
    name: funding
datasources:
  default:
    url: jdbc:mysql://localhost:3306/funding
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    schema-generate: NONE
    dialect: MYSQL
liquibase:
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.xml'
      drop-first: false
      enabled: true