micronaut:
  application:
    name: stock
  server:
    port: 8080
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: changeThisSecretToALongSecureString

flyway:
  datasources:
    default:
      enabled: true
      clean-schema: false
      url: jdbc:postgresql://127.0.0.1:5432/postgres
      username: root
      password: root
      schemas: mn
      default-schema: mn
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    schema-generate: NONE
    dialect: POSTGRES

jpa:
  default:
    entity-scan:
      - "com.github.fabriciolfj.persistence"
    properties:
      hibernate:
        show_sql: false

hello:
  config:
    greeting:
      br: "Ola"
      en: "Hello"
  controller: 
    path: /hello
msg:
  hello: Hello world

# JSON settings
jackson:
  property-naming-strategy: SNAKE_CASE
  generator:
    writeNumbersAsStrings: true
    writeBigDecimalAsPlain: true
  deserialization:
    failOnUnknownProperties: false
  serialization:
    writeDatesAsTimestamps: false
    writeDatesWithZoneId: true
    writeDateTimestampsAsNanoseconds: false